trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Deploy
  displayName: Deploy to kubernetes
  jobs:
  - job: Deploy
    displayName: Deploy
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: KubernetesManifest@0
      inputs:
        action: 'deploy'
        kubernetesServiceConnection: 'abby-test-connection'
        namespace: 'abby-test'
        manifests: 'manifests/*'
    - task: KubernetesManifest@0
      inputs:
        action: 'delete'
        kubernetesServiceConnection: 'abby-test-connection'
        namespace: 'abby-test'
        arguments: deployment app1nginxaks
